#!/bin/bash

function backup_system()
{
	sudo rsync --archive  --xattrs --partial --append --append-verify --progress --delete \
 	--exclude={,/dev/*,/proc/*,/sys/*,/tmp/*,/run/*,/mnt/*,/media/*,/lost+found,} / \
 	-e ssh / USER@IP:/backup_dir/
}

backup_system

exit 0

 sudo rsync --archive  --xattrs --partial --append --append-verify --progress --delete \
 	# archive  preserves premissions, owners, groups, symlinks, and special files
 	#          and acts recursively
   	# xattrs   preserves extended attributes
        # parital  keeps partially transferred files
        # append   resumes partially transferred files
	# progress shows transfer progress
	# delete   delete old files in destination
 --exclude={,/dev/*,/proc/*,/sys/*,/tmp/*,/run/*,/mnt/*,/media/*,/lost+found,} / \
	# exlcude these virtual, temporary, and device directories 
 -e ssh / USER@IP:/backup_dir/
	# backup rootdir('/') to user@IP:/backup_dir/ over ssh

# As a cronjob:
0 	12	*	*	*	/this/script/ 	


